---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
# Tasks for role automated
#
# Overview:
#
# This role is included as a dependency by other roles which provide
# automated jobs.  Automation occurs over ssh.  The automator user
# is assigned to a managed rbash shell and is, potentially, allowed to run
# explicitly listed commands via sudo.  Both the commands that are
# allowed via rbash and the sudoers file are provided by the
# including role.
#
# Dependencies:
#
# This role depends upon variables provided by an including role
# via the my_role/meta/main.yml file.  Includes take the following forms:
#
#  dependencies:
#   - role: automated
#     automated_rbash_links: "{{ edxapp_automated_rbash_links }}"
#     automated_sudoers_template: 'roles/edxapp/templates/etc/sudoers.d/99-automator-edxapp-server.j2'
#     automated_authorized_keys: "{{ EDXAPP_AUTOMATOR_AUTHORIZED_KEYS }}"
#
# The sudoers file is optional.  Note that for sudo to work it must be
# included in the rbash links list.
#
# That list should be provided via my_role's defaults
#
# role_automated_rbash_links:
#   - /usr/bin/sudo
#   - /usr/bin/scp
#

- fail: automated_rbash_links required for role
  when: AUTOMATED_RBASH_LINKS is not defined

- fail: automated_authorized_keys required for role
  when: AUTOMATED_AUTHORIZED_KEYS is not defined

- name: Create automated user
  user:
    name: "{{ AUTOMATED_USER }}"
    state: "present"
    shell: "/bin/rbash"
    home: "{{ automated_home }}"
    createhome: "yes"

- name: Create sudoers file from template
  template:
    dest: "/etc/sudoers.d/{{ AUTOMATED_SUDOERS_TEMPLATE|basename|replace('.j2','') }}"
    #dest: "/tmp/foo"
    src: "{{ AUTOMATED_SUDOERS_TEMPLATE }}"
    owner: "root"
    group: "root"
    mode: "0440"
    validate: 'visudo -cf %s'
  when: AUTOMATED_SUDOERS_TEMPLATE

  #
  # Prevent user from updating their PATH and
  # environment.
  #
- name: Update shell file mode
  file:
    path: "{{ automated_home }}/{{ item }}"
    mode: "0640"
    state: "file"
    owner: "root"
    group: "{{ AUTOMATED_USER }}"
  with_items:
    - .bashrc
    - .profile
    - .bash_logout

- name: Change ~automated ownership
  file:
    path: "{{ automated_home }}"
    mode: "0750"
    state: "directory"
    owner: "root"
    group: "{{ AUTOMATED_USER }}"

- name: Create ~automated/bin directory
  file:
    path: "{{ automated_home }}/bin"
    state: "directory"
    mode: "0750"
    owner: "root"
    group: "{{ AUTOMATED_USER }}"

- name: Create .ssh directory
  file:
    path: "{{ automated_home }}/.ssh"
    state: "directory"
    mode: "0400"
    owner: "{{ AUTOMATED_USER }}"
    group: "{{ AUTOMATED_USER }}"

- name: Build authorized_keys file
  template:
    src: "home/automator/.ssh/authorized_keys.j2"
    dest: "{{ automated_home }}/.ssh/authorized_keys"
    mode: "0600"
    owner: "{{ AUTOMATED_USER }}"
    group: "{{ AUTOMATED_USER }}"

- name: Build know_hosts file
  file:
    path: "{{ automated_home }}/.ssh/known_hosts"
    state: "touch"
    mode: "0755"
    owner: "{{ AUTOMATED_USER }}"
    group: "{{ AUTOMATED_USER }}"
  
- name: Create allowed command links
  file:
    src: "{{ item }}"
    dest: "{{ automated_home }}/bin/{{ item.split('/').pop() }}"
    state: "link"
  with_items: AUTOMATED_RBASH_LINKS
