---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Defaults for role demo
#

DEMO_CREATE_STAFF_USER: true

oxa_demo_app_dir: "{{ COMMON_APP_DIR }}/oxa_demo"
oxa_demo_code_dir: "{{ oxa_demo_app_dir }}/oxa_kitchen_sink"
oxa_demo_repo: "https://{{ COMMON_GIT_MIRROR }}/microsoft/oxa_kitchen_sink.git"
oxa_demo_course_id: 'course-v1:Microsoft+KS101+course'
oxa_demo_version: "oxa/master.fic"
oxa_demo_edxapp_user: 'edxapp'
oxa_demo_edxapp_settings: '{{ COMMON_EDXAPP_SETTINGS }}'
oxa_demo_edxapp_venv_bin: '{{ COMMON_APP_DIR }}/{{ oxa_demo_edxapp_user }}/venvs/{{oxa_demo_edxapp_user}}/bin'
oxa_demo_edxapp_course_data_dir: '{{ COMMON_DATA_DIR }}/{{ oxa_demo_edxapp_user }}/data'
oxa_demo_edxapp_code_dir: '{{ COMMON_APP_DIR }}/{{ oxa_demo_edxapp_user }}/edx-platform'