- name: Deploy MongoDB
  hosts: all
  sudo: True
  gather_facts: True
  roles:
    - mongo
    # Doesn't work in default case, not MMSAPIKEY
    #    - mongo_mms
    - role: datadog
      when: COMMON_ENABLE_DATADOG
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
