---

- name: check out the demo course
  git:
    dest: "{{ oxa_demo_code_dir }}"
    repo: "{{ oxa_demo_repo }}"
    version: "{{ oxa_demo_version }}"
    accept_hostkey: yes
  become_user: "{{ oxa_demo_edxapp_user }}"
  register: oxa_demo_checkout

- name: import demo course
  shell: "{{ oxa_demo_edxapp_venv_bin }}/python ./manage.py cms --settings={{ oxa_demo_edxapp_settings }} import {{ oxa_demo_edxapp_course_data_dir }} {{ oxa_demo_code_dir }}"
  args:
    chdir: "{{ oxa_demo_edxapp_code_dir }}"
  become_user: "{{ oxa_common_web_user }}"
  when: demo_checkout.changed

