---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role otto_multitenant_setup
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#
- debug: msg="Vars from otto_multitenant_setup role"
- debug: msg="COMMON_BIN_DIR - {{ COMMON_BIN_DIR }}"
- debug: msg="EDXAPP_LMS_BASE - {{ EDXAPP_LMS_BASE }}"
- debug: msg="ECOMMERCE_ECOMMERCE_URL_ROOT - {{ ECOMMERCE_ECOMMERCE_URL_ROOT }}"
- debug: msg="ecommerce_user - {{ ecommerce_user }}"
- debug: msg="ecommerce_environment - {{ ecommerce_environment }}"
- debug: msg="EDXAPP_SITE_NAME - {{ EDXAPP_SITE_NAME }}"

- name: Setup Site and Site Configurations for Otto
  shell: >
    {{ COMMON_BIN_DIR }}/python.ecommerce {{ COMMON_BIN_DIR }}/manage.ecommerce create_or_update_site
    --settings=ecommerce.settings.production
    --site-domain='ecommerce-{{ EDXAPP_LMS_BASE }}'
    --site-name='ecommerce-{{ ECOMMERCE_ECOMMERCE_URL_ROOT }}'
    --partner-code='edx'
    --partner-name='edx'
    --lms-url-root='{{ ECOMMERCE_LMS_URL_ROOT }}'
    --theme-scss-path='sass'
    --payment-processors='cybersource,paypal'
    --client-id='ecommerce-key'
    --client-secret='ecommerce-secret'
    --from-email='sandbox-notifications@edx.org'
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
