---
- name: Install snort
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - snort
    - oinkmaster

- name: Configure snort and snort (debian)
  template:
    src: "etc/snort/{{ item }}"
    dest: "/etc/snort/{{ item.rstrip('.j2') }}"
    owner: root
    group: root
    mode: "0644"
  with_items:
    - snort.conf.j2
    - snort.debian.conf.j2

- name: Configure oinkmaster
  template:
    src: "etc/oinkmaster.conf.j2"
    dest: "/etc/oinkmaster.conf"
    owner: root
    group: root
    mode: "0644"

- name: Update snort
  shell: "oinkmaster -C /etc/oinkmaster.conf -o /etc/snort/rules/"
  become: yes

- name: Snort service
  service:
    name: snort
    state: started

- name: Open read permissions on snort logs
  file:
    name: "/var/log/snort"
    state: directory
    mode: "0755"

- name: Install oinkmaster cronjob
  template:
    src: "etc/cron.daily/oinkmaster.j2"
    dest: "/etc/cron.daily/oinkmaster"
    owner: root
    group: root
    mode: "0755"
