---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Vars for role splunk
#

#
# vars are namespace with the module name.
#
splunk_role_name: 'splunk'

SPLUNKFORWARDER_PACKAGE_URL: !!null
SPLUNKFORWARDER_DEB: !!null
SPLUNKFORWARDER_PASSWORD: !!null

# A list of dicts with the following keys:
#   target_group: the name of the group
#   server: the hostname/IP address of the splunk server
#   default: whether this group is the default logging group
#
# The following keys are for use with SSL. They must all be defined to enable SSL.
#   ssl_cert: text of the SSL cert to use
#   ssl_password: the password of the cert
#   ssl_common_name: the hostname associated with the cert
SPLUNKFORWARDER_SERVERS:
  - target_group: "default_output_server"
    server: "localhost:9997"
    default: true

# The signing CA cert for the certs used in SPLUNKFORWARDER_SERVERS
SPLUNKFORWARDER_ROOT_CA: !!null

SPLUNKFORWARDER_LOG_ITEMS:
  - source: '{{ COMMON_LOG_DIR }}/lms'
    recursive: true
    index: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}'
    sourcetype: 'edx'
  - source: '{{ COMMON_LOG_DIR }}/cms'
    recursive: true
    index: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}'
    sourcetype: 'edx'
  - source: '{{ COMMON_LOG_DIR }}/mongo'
    recursive: true
    index: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}'
    sourcetype: 'mongo'
  - source: '{{ COMMON_LOG_DIR }}'
    recursive: true
    index: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}'
    sourcetype: 'syslog'
  - source: '/var/log'
    recursive: true
    index: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}'
    sourcetype: 'syslog'
  - source: '{{ COMMON_LOG_DIR }}/nginx'
    recursive: true
    index: '{{ COMMON_ENVIRONMENT }}-{{ COMMON_DEPLOYMENT }}'
    sourcetype: 'nginx'

#
# OS packages
#
splunk_debian_pkgs:
  - gdebi

splunk_redhat_pkgs: []

splunkforwarder_output_dir: '/opt/splunkforwarder/'
splunkforwarder_ssl_cert_path: 'etc/auth/edxcerts'
