---
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://github.com/edx/configuration/wiki
# code style: https://github.com/edx/configuration/wiki/Ansible-Coding-Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
##
# Vars for role automated
#

#
# vars are namespace with the module name.
#
automated_role_name: automated
AUTOMATED_USER: "changeme"
automated_home: "/home/{{ AUTOMATED_USER }}"
AUTOMATED_RBASH_LINKS: !!null
AUTOMATED_SUDOERS_TEMPLATE: !!null

#
# OS packages
#

automated_debian_pkgs: []

automated_redhat_pkgs: []
