---

# Stateful app server configuration, designed to be used with 
# external mysql & mongo and local rabbitmq & elasticsearch services.

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True

  vars:
    migrate_db: 'yes'
    openid_workaround: True
    EDXAPP_LMS_NGINX_PORT: '80'
    ENABLE_ECOMMERCE: False  # Disable ecommerce by default
  roles:

    # Ensure we have no known security vulnerabilities
    - security

    # Server setup
    - swapfile

    # Nginx reverse proxy
    - role: azure-mysql
      
    # Main EdX application
    # https://github.com/edx/edx-platform
    - role: rabbitmq
      rabbitmq_ip: 127.0.0.1
      when: SANDBOX_ENABLE_RABBITMQ
    - role: elasticsearch
      when: "'localhost' in EDXAPP_ELASTIC_SEARCH_CONFIG|map(attribute='host')"